### ISSUE TITLE
Scalda License

### ISSUE THREAD

**Issue by onema** [Nitro/scalda#7]
What type of license you have for this project?

**Comment by onema** [comment]
Bump?

**Comment by mihaitodor** [comment]
@onema Thank you for reporting this issue! It's an oversight on our side. I'll update the repo as soon as possible with a suitable license.

**Comment by mihaitodor** [comment]
@onema This is fixed now. I hope the license is suitable for you.

**Comment by onema** [comment]
This is great, Thanks!!

**Comment by mihaitodor** [comment]
You're welcome! :)
